blank_issues_enabled: false
contact_links:
  - name: prismix.new related issues
    url: https://github.com/Mindinu/prismix.new/issues/new/choose
    about: Report issues related to prismix.new (not prismix.new)
  - name: Chat
    url: https://thinktank.ottomator.ai
    about: Ask questions and discuss with other prismix.new users.
